name: Build Touch

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "touch/**"
      - "!touch/*.md"
  push:
    branches:
      - main
    paths:
      - "touch/**"
      - "!touch/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Touch
    runs-on: windows-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build Touch
      run: |
        cd touch
        cargo build --release

    - name: Upload Touch
      uses: actions/upload-artifact@v4
      with:
        name: touch-windows-x86_64-0.1.0
        path: touch/target/release/*.exe
